/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: albertomarun (https://sketchfab.com/albertomarun)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/d2be38faf4124fb9839853bedce5bcce
title: Star Wars - Halcon Milenario
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF("/scene.gltf")
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.CP_Front} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.Cockpit2} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.Cockpit3} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials.Dish01} />
        <mesh geometry={nodes.mesh_4.geometry} material={materials.Dish02} />
        <mesh geometry={nodes.mesh_5.geometry} material={materials.DrivBack} />
        <mesh geometry={nodes.mesh_6.geometry} material={materials.Engine01} />
        <mesh geometry={nodes.mesh_7.geometry} material={materials.Engine02} />
        <mesh geometry={nodes.mesh_8.geometry} material={materials.M_Inside} />
        <mesh geometry={nodes.mesh_9.geometry} material={materials.MandbEnd} />
        <mesh geometry={nodes.mesh_10.geometry} material={materials.PodSide1} />
        <mesh geometry={nodes.mesh_11.geometry} material={materials.SidePort} />
        <mesh geometry={nodes.mesh_12.geometry} material={materials.SideRear} />
        <mesh geometry={nodes.mesh_13.geometry} material={materials.SideRear1} />
        <mesh geometry={nodes.mesh_14.geometry} material={materials.Turret_L} />
        <mesh geometry={nodes.mesh_15.geometry} material={materials.DishSide} />
        <mesh geometry={nodes.mesh_16.geometry} material={materials.EscPod_L} />
        <mesh geometry={nodes.mesh_17.geometry} material={materials.EscPod_U} />
        <mesh geometry={nodes.mesh_18.geometry} material={materials.FalcPlan} />
        <mesh geometry={nodes.mesh_19.geometry} material={nodes.mesh_19.material} />
        <mesh geometry={nodes.mesh_20.geometry} material={nodes.mesh_20.material} />
        <mesh geometry={nodes.mesh_21.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.mesh_22.geometry} material={materials.Hatch} />
        <mesh geometry={nodes.mesh_23.geometry} material={materials.Turret_U} />
        <mesh geometry={nodes.mesh_24.geometry} material={materials.Vent01} />
        <mesh geometry={nodes.mesh_25.geometry} material={materials.Charcoal_1} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
